// ============================================================================
// Brand Builder Types
// Types for the unified Brand Builder conversational flow
// ============================================================================

/**
 * The phases of the Brand Builder flow
 */
export type BuilderPhase =
  | 'research'      // Phase 1: Document upload + AI questions
  | 'overview'      // Phase 2: Draft brand overview
  | 'customer'      // Phase 3: Draft target customer
  | 'style_guide'   // Phase 4: Copy samples + style guide
  | 'dos_donts'     // Phase 5: Do's and Don'ts
  | 'complete';     // All phases done

/**
 * Phase metadata for UI display
 */
export interface PhaseInfo {
  id: BuilderPhase;
  label: string;
  description: string;
  icon: string;
  outputField?: keyof BrandBuilderDrafts;
}

export const BUILDER_PHASES: PhaseInfo[] = [
  {
    id: 'research',
    label: 'Research & Intake',
    description: 'Upload documents and answer questions about your brand',
    icon: 'search',
  },
  {
    id: 'overview',
    label: 'Brand Overview',
    description: 'Create a concise brand description',
    icon: 'file-text',
    outputField: 'brandOverview',
  },
  {
    id: 'customer',
    label: 'Target Customer',
    description: 'Define who your ideal customer is',
    icon: 'users',
    outputField: 'targetCustomer',
  },
  {
    id: 'style_guide',
    label: 'Copywriting Style',
    description: 'Develop your brand voice through copy samples',
    icon: 'pen-tool',
    outputField: 'copywritingStyleGuide',
  },
  {
    id: 'dos_donts',
    label: "Do's & Don'ts",
    description: 'Set clear guidelines for your brand communication',
    icon: 'check-circle',
    outputField: 'dosDonts',
  },
];

/**
 * A copy sample generated by AI for the style guide phase
 */
export interface CopySample {
  id: string;
  type: 'subject_line' | 'hero' | 'body' | 'cta' | 'tagline';
  content: string;
  tone: string;
}

/**
 * A single do or don't item
 */
export interface DoOrDont {
  id: string;
  type: 'do' | 'dont';
  content: string;
}

/**
 * Message metadata for builder conversations
 */
export interface BuilderMessageMetadata {
  /** Copy samples included in this message */
  copySamples?: CopySample[];
  /** Suggested output text (draft for current phase) */
  suggestedOutput?: string;
  /** Document IDs referenced in this message */
  documentReferences?: string[];
  /** Do's and Don'ts suggested in this message */
  suggestedDosDonts?: DoOrDont[];
}

/**
 * A message in the Brand Builder conversation
 */
export interface BuilderMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  phase: BuilderPhase;
  metadata?: BuilderMessageMetadata;
  createdAt: string;
}

/**
 * Draft outputs for each phase
 */
export interface BrandBuilderDrafts {
  brandOverview?: string;
  targetCustomer?: string;
  copywritingStyleGuide?: string;
  dosDonts?: DoOrDont[];
}

/**
 * The complete Brand Builder state stored in the database
 */
export interface BrandBuilderState {
  currentPhase: BuilderPhase;
  conversationHistory: BuilderMessage[];
  draftOutputs: BrandBuilderDrafts;
  uploadedDocumentIds: string[];
  lastUpdatedAt: string;
}

/**
 * API request body for Brand Builder interactions
 */
export interface BrandBuilderRequest {
  brandId: string;
  action:
    | 'start_phase'      // Begin a new phase
    | 'continue'         // Continue conversation in current phase
    | 'approve_draft'    // Approve draft and move to next phase
    | 'request_samples'  // Generate new copy samples (style_guide phase)
    | 'save_state'       // Just persist state, no AI response
    | 'finalize';        // Complete the builder, save all outputs
  phase?: BuilderPhase;
  userMessage?: string;
  conversationHistory?: BuilderMessage[];
  currentDrafts?: BrandBuilderDrafts;
  uploadedDocumentIds?: string[];
}

/**
 * API response for Brand Builder
 */
export interface BrandBuilderResponse {
  message: string;
  phase: BuilderPhase;
  metadata?: BuilderMessageMetadata;
  /** Updated drafts after this interaction */
  updatedDrafts?: BrandBuilderDrafts;
  /** Whether to advance to next phase */
  advancePhase?: boolean;
  /** Error message if any */
  error?: string;
}

/**
 * Props for phase components
 */
export interface PhaseComponentProps {
  brandId: string;
  brandName: string;
  state: BrandBuilderState;
  onStateChange: (state: BrandBuilderState) => void;
  onPhaseComplete: (phase: BuilderPhase, output: string | DoOrDont[]) => void;
  onBack: () => void;
}

/**
 * Create a new empty Brand Builder state
 */
export function createEmptyBuilderState(): BrandBuilderState {
  return {
    currentPhase: 'research',
    conversationHistory: [],
    draftOutputs: {},
    uploadedDocumentIds: [],
    lastUpdatedAt: new Date().toISOString(),
  };
}

/**
 * Get the next phase in the flow
 */
export function getNextPhase(current: BuilderPhase): BuilderPhase | null {
  const order: BuilderPhase[] = ['research', 'overview', 'customer', 'style_guide', 'dos_donts', 'complete'];
  const currentIndex = order.indexOf(current);
  if (currentIndex === -1 || currentIndex >= order.length - 1) return null;
  return order[currentIndex + 1];
}

/**
 * Get the previous phase in the flow
 */
export function getPreviousPhase(current: BuilderPhase): BuilderPhase | null {
  const order: BuilderPhase[] = ['research', 'overview', 'customer', 'style_guide', 'dos_donts', 'complete'];
  const currentIndex = order.indexOf(current);
  if (currentIndex <= 0) return null;
  return order[currentIndex - 1];
}

/**
 * Check if a phase is complete based on drafts
 */
export function isPhaseComplete(phase: BuilderPhase, drafts: BrandBuilderDrafts): boolean {
  switch (phase) {
    case 'research':
      // Research is complete when we have any context (always allow proceeding)
      return true;
    case 'overview':
      return !!drafts.brandOverview && drafts.brandOverview.trim().length > 0;
    case 'customer':
      return !!drafts.targetCustomer && drafts.targetCustomer.trim().length > 0;
    case 'style_guide':
      return !!drafts.copywritingStyleGuide && drafts.copywritingStyleGuide.trim().length > 0;
    case 'dos_donts':
      return !!drafts.dosDonts && drafts.dosDonts.length > 0;
    case 'complete':
      return true;
    default:
      return false;
  }
}

/**
 * Get completion percentage for the builder
 */
export function getBuilderProgress(state: BrandBuilderState): number {
  const phases: BuilderPhase[] = ['research', 'overview', 'customer', 'style_guide', 'dos_donts'];
  let completed = 0;

  for (const phase of phases) {
    if (isPhaseComplete(phase, state.draftOutputs)) {
      completed++;
    }
  }

  // If current phase is complete, we're past it
  if (state.currentPhase === 'complete') {
    return 100;
  }

  return Math.round((completed / phases.length) * 100);
}
