/**
 * Email Generation Agent using AI SDK 6.0 ToolLoopAgent
 *
 * An autonomous agent that can analyze brands, search the web,
 * and generate high-quality email copy with A/B/C variants.
 */

import 'server-only';
import { ToolLoopAgent, InferAgentUIMessage, tool, ToolSet } from 'ai';
import { z } from 'zod';
import { gateway, createWebSearchTool } from '../ai-providers';
import { MODELS } from '../ai-constants';

// ============================================================================
// SCHEMAS
// ============================================================================

const BrandAnalysisSchema = z.object({
  brandName: z.string().describe('Name of the brand'),
  brandDetails: z.string().optional().describe('Brand details and description'),
  styleGuide: z.string().optional().describe('Copywriting style guide'),
  websiteUrl: z.string().optional().describe('Brand website URL'),
});

type BrandAnalysisInput = z.infer<typeof BrandAnalysisSchema>;

const EmailVariantsSchema = z.object({
  emailType: z.enum(['promotional', 'welcome', 'abandoned_cart', 'winback', 'announcement']).describe('Type of email'),
  objective: z.string().describe('Main objective of the email'),
  keyMessages: z.array(z.string()).describe('Key messages to include'),
  cta: z.string().describe('Call to action'),
  brandVoice: z.string().optional().describe('Brand voice/tone to use'),
});

type EmailVariantsInput = z.infer<typeof EmailVariantsSchema>;

const EmailArtifactSchema = z.object({
  title: z.string().describe('Title for the email artifact'),
  versions: z.array(z.object({
    id: z.enum(['a', 'b', 'c']),
    label: z.string(),
    subject_line: z.string(),
    preview_text: z.string(),
    approach: z.string(),
    content: z.string(),
  })).describe('Email versions A, B, and C'),
  selectedVariant: z.enum(['a', 'b', 'c']).default('a'),
  emailType: z.string().optional(),
});

type EmailArtifactInput = z.infer<typeof EmailArtifactSchema>;

// ============================================================================
// AGENT TOOLS
// ============================================================================

/**
 * Brand analysis tool - analyzes the brand context
 */
const analyzeBrandTool = tool({
  description: 'Analyze the brand context to understand voice, tone, and messaging guidelines',
  inputSchema: BrandAnalysisSchema,
  execute: async (input: BrandAnalysisInput) => {
    const { brandName, styleGuide, websiteUrl } = input;
    
    // Extract key brand attributes
    const analysis = {
      name: brandName,
      hasWebsite: !!websiteUrl,
      voiceIndicators: [] as string[],
      toneKeywords: [] as string[],
      targetAudience: 'general',
    };

    // Parse style guide for voice indicators
    if (styleGuide) {
      const lowerGuide = styleGuide.toLowerCase();
      if (lowerGuide.includes('friendly') || lowerGuide.includes('casual')) {
        analysis.voiceIndicators.push('friendly', 'approachable');
      }
      if (lowerGuide.includes('professional') || lowerGuide.includes('formal')) {
        analysis.voiceIndicators.push('professional', 'authoritative');
      }
      if (lowerGuide.includes('playful') || lowerGuide.includes('fun')) {
        analysis.voiceIndicators.push('playful', 'energetic');
      }
    }

    return {
      success: true,
      analysis,
      recommendations: [
        `Use ${analysis.voiceIndicators.join(', ') || 'professional'} tone`,
        websiteUrl ? 'Reference products from website' : 'Focus on brand values',
      ],
    };
  },
});

/**
 * Generate email variants tool
 */
const generateEmailVariantsTool = tool({
  description: 'Generate A/B/C email copy variants with different approaches',
  inputSchema: EmailVariantsSchema,
  execute: async (input: EmailVariantsInput) => {
    const { emailType, objective, keyMessages, cta, brandVoice } = input;
    
    // Generate framework for variants - actual content generated by AI
    return {
      variants: [
        {
          id: 'a',
          approach: 'Urgency-driven',
          focus: 'Create FOMO and immediate action',
          suggestedElements: ['countdown timer', 'limited quantity', 'exclusive access'],
        },
        {
          id: 'b',
          approach: 'Value-focused',
          focus: 'Highlight benefits and value proposition',
          suggestedElements: ['customer benefits', 'social proof', 'feature highlights'],
        },
        {
          id: 'c',
          approach: 'Story-led',
          focus: 'Connect emotionally through narrative',
          suggestedElements: ['brand story', 'customer journey', 'emotional connection'],
        },
      ],
      sharedGuidelines: {
        emailType,
        objective,
        keyMessages,
        cta,
        brandVoice: brandVoice || 'professional yet approachable',
      },
    };
  },
});

/**
 * Create email artifact tool
 */
const createEmailArtifactTool = tool({
  description: 'Create a persistent email artifact with all variants',
  inputSchema: EmailArtifactSchema,
  execute: async (input: EmailArtifactInput) => {
    const { title, versions, selectedVariant, emailType } = input;
    
    // Return the artifact structure - actual DB insertion handled by stream handler
    return {
      status: 'pending' as const,
      kind: 'email' as const,
      title,
      versions,
      selectedVariant,
      emailType,
      message: 'Artifact will be created by the server',
    };
  },
});

// ============================================================================
// AGENT TOOLS TYPE
// ============================================================================

const baseTools = {
  analyze_brand: analyzeBrandTool,
  generate_email_variants: generateEmailVariantsTool,
  create_email_artifact: createEmailArtifactTool,
};

// ============================================================================
// AGENT DEFINITION
// ============================================================================

/**
 * Create the email generation agent
 */
export function createEmailAgent(brandContext?: {
  name?: string;
  brand_details?: string;
  copywriting_style_guide?: string;
  website_url?: string;
}) {
  const websiteUrl = brandContext?.website_url;

  // Build instructions with brand context
  const instructions = `You are an expert email copywriter agent for ${brandContext?.name || 'brands'}.

Your capabilities:
1. Analyze brands to understand voice, tone, and messaging
2. Search the web for product information and market trends
3. Generate A/B/C email variants with different strategic approaches
4. Create persistent artifacts for the user to iterate on

${brandContext?.copywriting_style_guide ? `
BRAND VOICE GUIDELINES:
${brandContext.copywriting_style_guide}
` : ''}

WORKFLOW:
1. First, analyze the brand context using the analyze_brand tool
2. If needed, search the web for product/market information
3. Generate variant frameworks using generate_email_variants tool
4. Write the full email copy for each variant
5. Create the artifact using create_email_artifact tool

Always generate 3 distinct variants (A, B, C) with different approaches:
- Version A: Urgency-driven (FOMO, scarcity, time-limited)
- Version B: Value-focused (benefits, features, social proof)
- Version C: Story-led (emotional, narrative, connection)

Each variant MUST include:
- Subject line (max 50 chars with emoji option)
- Preview text (max 100 chars)
- Full email body in markdown format`;

  // Build tools set
  const tools: ToolSet = { ...baseTools };

  // Add web search if available
  if (websiteUrl) {
    try {
      tools.web_search = createWebSearchTool(websiteUrl);
    } catch {
      // Web search not available, continue without it
    }
  }

  return new ToolLoopAgent({
    model: gateway.languageModel(MODELS.CLAUDE_SONNET),
    instructions,
    tools,
    stopWhen: (result) => result.steps.length >= 10,
  });
}

/**
 * Type for agent UI messages
 */
export type EmailAgentMessage = InferAgentUIMessage<ReturnType<typeof createEmailAgent>>;

// ============================================================================
// AGENT UTILITIES
// ============================================================================

/**
 * Run the email agent with a brief (non-streaming)
 */
export async function runEmailAgent(
  brief: string,
  brandContext?: Parameters<typeof createEmailAgent>[0]
) {
  const agent = createEmailAgent(brandContext);

  // The agent will autonomously:
  // 1. Analyze the brand
  // 2. Search for relevant info
  // 3. Generate variants
  // 4. Create the artifact

  return agent.generate({
    prompt: brief,
  });
}

/**
 * Stream the email agent response
 */
export async function streamEmailAgent(
  brief: string,
  brandContext?: Parameters<typeof createEmailAgent>[0]
) {
  const agent = createEmailAgent(brandContext);

  return agent.stream({
    prompt: brief,
  });
}
