-- ============================================================================
-- Brand Builder Migration
-- Adds support for the unified Brand Builder feature
-- ============================================================================

-- Add new columns to brands table for Brand Builder
ALTER TABLE brands
ADD COLUMN IF NOT EXISTS brand_overview TEXT,           -- 1-2 paragraph brand overview
ADD COLUMN IF NOT EXISTS target_customer TEXT,          -- 1 paragraph target customer description
ADD COLUMN IF NOT EXISTS brand_builder_state JSONB;     -- Builder state for resume/history

-- Add comment for documentation
COMMENT ON COLUMN brands.brand_overview IS 'Concise 1-2 paragraph brand overview generated by Brand Builder';
COMMENT ON COLUMN brands.target_customer IS 'Target customer description paragraph generated by Brand Builder';
COMMENT ON COLUMN brands.brand_builder_state IS 'Brand Builder state for resuming sessions. Contains: current_phase, conversation_history, draft_outputs, uploaded_document_ids, last_updated_at';

-- Create index on brand_builder_state for querying by phase
CREATE INDEX IF NOT EXISTS idx_brands_builder_phase
ON brands ((brand_builder_state->>'current_phase'))
WHERE brand_builder_state IS NOT NULL;
