/**
 * Output tools - Create conversation and send notifications
 */

import { tool } from 'npm:ai@4'
import { z } from 'npm:zod@3'
import type { SupabaseClient } from 'jsr:@supabase/supabase-js@2'
import { Resend } from 'npm:resend@4'

const resendApiKey = Deno.env.get('RESEND_API_KEY')
const resend = resendApiKey ? new Resend(resendApiKey) : null
const emailFrom = Deno.env.get('EMAIL_FROM') || 'insights@mooncommerce.net'
const appUrl = Deno.env.get('APP_URL') || Deno.env.get('NEXT_PUBLIC_APP_URL') || 'https://mccopycommandcenter.vercel.app'

export function createConversationTool(supabase: SupabaseClient) {
  return tool({
    description: 'Create a new conversation with the generated insights, pinned in the user\'s workspace',
    parameters: z.object({
      brandId: z.string().describe('The brand ID'),
      userId: z.string().describe('The user ID'),
      title: z.string().describe('Title for the conversation'),
      content: z.string().describe('The full insights content to save as the first AI message'),
      insightType: z.enum(['daily', 'weekly', 'manual']).describe('Type of insight'),
    }),
    execute: async ({ brandId, userId, title, content, insightType }) => {
      try {
        // Create the conversation
        const { data: conversation, error: convError } = await supabase
          .from('conversations')
          .insert({
            brand_id: brandId,
            user_id: userId,
            title,
            model: 'openai/gpt-4o',
            conversation_type: 'email',
            mode: 'planning',
            is_pinned: true, // Pin so it's visible
            created_by_name: 'Marketing Agent',
            last_message_preview: content.substring(0, 100) + '...',
            last_message_at: new Date().toISOString(),
          })
          .select('id')
          .single()

        if (convError || !conversation) {
          console.error('[Output Tool] Error creating conversation:', convError)
          throw new Error(`Failed to create conversation: ${convError?.message}`)
        }

        // Create system context message
        await supabase.from('messages').insert({
          conversation_id: conversation.id,
          role: 'system',
          content: `This is an automated ${insightType} marketing insights conversation generated by the Marketing Agent. The user can reply to discuss any ideas, ask for more details, or request the AI to write specific campaigns.`,
          user_id: userId,
        })

        // Create the AI insights message
        await supabase.from('messages').insert({
          conversation_id: conversation.id,
          role: 'assistant',
          content,
          user_id: userId,
          metadata: {
            generated_by: 'marketing_agent',
            insight_type: insightType,
            generated_at: new Date().toISOString(),
          },
        })

        console.log(`[Output Tool] Created conversation ${conversation.id} for brand ${brandId}`)

        return {
          success: true,
          conversationId: conversation.id,
          title,
        }
      } catch (error) {
        console.error('[Output Tool] Error:', error)
        return {
          success: false,
          error: error instanceof Error ? error.message : 'Unknown error',
        }
      }
    },
  })
}

export function createNotificationTool(supabase: SupabaseClient) {
  return tool({
    description: 'Send notification (in-app and optionally email) about new insights',
    parameters: z.object({
      userId: z.string().describe('User ID to notify'),
      userEmail: z.string().optional().describe('User email for email notification'),
      userName: z.string().optional().describe('User name for personalization'),
      brandId: z.string().describe('Brand ID'),
      brandName: z.string().describe('Brand name'),
      conversationId: z.string().describe('ID of the created conversation'),
      title: z.string().describe('Title of the insights'),
      insightType: z.enum(['daily', 'weekly', 'manual']).describe('Type of insight'),
      sendEmail: z.boolean().default(true).describe('Whether to send email notification'),
    }),
    execute: async ({
      userId,
      userEmail,
      userName,
      brandId,
      brandName,
      conversationId,
      title,
      insightType,
      sendEmail,
    }) => {
      try {
        // Create in-app notification
        const { error: notifError } = await supabase.from('notifications').insert({
          user_id: userId,
          type: 'agent_insight',
          title: `${insightType === 'daily' ? '📧' : '📊'} ${title}`,
          message: `Your ${insightType} marketing insights for ${brandName} are ready`,
          link: `/brands/${brandId}/chat?conversation=${conversationId}`,
          metadata: {
            brand_id: brandId,
            conversation_id: conversationId,
            insight_type: insightType,
          },
        })

        if (notifError) {
          console.error('[Notification Tool] Error creating notification:', notifError)
        }

        // Send email if enabled and configured
        if (sendEmail && userEmail && resend) {
          const conversationUrl = `${appUrl}/brands/${brandId}/chat?conversation=${conversationId}`
          const firstName = userName?.split(' ')[0] || 'there'

          const emailHtml = `
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <style>
      body { 
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
        line-height: 1.6;
        color: #1a1a2e;
        background-color: #f5f5f7;
        margin: 0;
        padding: 0;
      }
      .container {
        max-width: 560px;
        margin: 40px auto;
        background: white;
        border-radius: 12px;
        box-shadow: 0 2px 8px rgba(0,0,0,0.06);
        overflow: hidden;
      }
      .header {
        background: linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%);
        padding: 24px 32px;
        text-align: center;
      }
      .header h1 {
        margin: 0;
        color: white;
        font-size: 20px;
        font-weight: 600;
      }
      .content {
        padding: 32px;
      }
      .button {
        display: inline-block;
        background: linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%);
        color: white !important;
        padding: 14px 28px;
        text-decoration: none;
        border-radius: 8px;
        font-weight: 600;
        margin: 20px 0;
      }
      .footer {
        padding: 24px 32px;
        background: #f8fafc;
        border-top: 1px solid #e2e8f0;
        font-size: 12px;
        color: #64748b;
        text-align: center;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="header">
        <h1>${insightType === 'daily' ? '📧' : '📊'} ${title}</h1>
      </div>
      <div class="content">
        <p>Hey ${firstName}!</p>
        <p>Your ${insightType} marketing insights for <strong>${brandName}</strong> are ready and waiting for you.</p>
        <p>${
          insightType === 'weekly'
            ? "This week's strategic review includes campaign analysis, market trends, and priority recommendations."
            : 'Fresh campaign ideas tailored to what\'s happening right now.'
        }</p>
        <div style="text-align: center;">
          <a href="${conversationUrl}" class="button">View Insights →</a>
        </div>
        <p style="color: #64748b; font-size: 14px;">
          This conversation is pinned in your workspace. You can chat with the insights to explore ideas further or request specific campaign copy.
        </p>
      </div>
      <div class="footer">
        <p>You're receiving this because you have agent insights enabled for ${brandName}.</p>
        <p><a href="${appUrl}/settings/agents" style="color: #6366f1;">Manage settings</a></p>
      </div>
    </div>
  </body>
</html>`

          try {
            await resend.emails.send({
              from: emailFrom,
              to: userEmail,
              subject: `${insightType === 'daily' ? '📧' : '📊'} ${title}`,
              html: emailHtml,
            })

            console.log(`[Notification Tool] Email sent to ${userEmail}`)
          } catch (emailError) {
            console.error('[Notification Tool] Error sending email:', emailError)
          }
        }

        return {
          success: true,
          notificationSent: true,
          emailSent: sendEmail && !!resend && !!userEmail,
        }
      } catch (error) {
        console.error('[Notification Tool] Error:', error)
        return {
          success: false,
          error: error instanceof Error ? error.message : 'Unknown error',
        }
      }
    },
  })
}

